pipeline {
  agent any
  stages{
    stage ('build') {
      steps {
        echo 'this is test'
      }
    }
    stage ('parallel') {
      parallel {
        stage ('unit test') {
          steps {
           echo 'this is test'
      }
    }
    stage ('deploy'){
    steps {
      echo 'this is deploy'
    }
  }
}
}
  }
}
